export {FormInput} from './Forminput/FormInput'
export {FormButton} from './FormButton/FormButton'
export {CheckB} from './checkBox/CheckBox'
export {GoogleButton} from './googleButton/GoogleButton'
export {FormPassword} from './Forminput/FormPassword'
export {FormEmail} from './Forminput/FormEmail'