export {FormInput} from './Forminput/FormInput'
export {FormButton} from './FormButton/FormButton'
export {CheckB} from './checkBox/CheckBox'
export {GoogleButton} from './googleButton/GoogleButton'
export {InputPassword} from './Forminput/InputPassword'
export {InputEmail} from './Forminput/InputEmail'
export {Footer} from './Footer/Footer'